instances:
  alpha:
    bundle: foundation
    working_dir: /mnt/c/Users/charl/OneDrive/Amplifier Data
    persona:
      name: Alpha
      emoji: ":robot_face:"
  
  beta:
    bundle: foundation
    working_dir: ~/amplifier-working-beta
    persona:
      name: Beta
      emoji: ":gear:"

defaults:
  instance: alpha

slack:
  app_token: ${SLACK_APP_TOKEN}
  bot_token: ${SLACK_BOT_TOKEN}
